# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00aa56a6728afc3ad022921437b5b4a7b9596b9aa1198d4848beb09004f0fae9c2ef6bd2347e0510f7c0de574ab7d62d8895d7bb20b01dff7091262c71fb096a

test:
  secret_key_base: 44d5ca4aab4935fcb34ee1fb96c7a554b804a2fab597afc87d17748e88564927edf3a27eb9eb7f771e2d06b42b6f090ef342d874aedd1d12562ab456d6b279ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
